name: Run Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Cypress dependencies
        working-directory: cypress-tests
        run: npm install

      - name: Run Cypress Tests in Chrome
        working-directory: cypress-tests
        run: npx cypress run --browser chrome

      - name: Run Cypress Tests in firefox
        working-directory: cypress-tests
        run: npx cypress run --browser chrome
